# Generated by Django 6.0.1 on 2026-01-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('product__name',), 'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзина'},
        ),
    ]
